"""Report generator tool — produces a PDF service report from conversation context.

Provides the ``generate_fix_report`` FunctionTool that the root agent calls
after a repair is completed (or whenever the user requests a report).

Workflow
--------
1. Receive a rich ``conversation_summary`` composed by the root agent.
2. Read ``processed_frames`` metadata from session state.
3. Call ``gemini-3-flash-preview`` with structured output to extract a
   well-formed ``ReportData`` dict (equipment info, diagnosis, steps,
   image selections, etc.).
4. Load selected images from ADK artifacts via ``tool_context.load_artifact``.
5. Build a styled PDF with FPDF2.
6. Save the PDF as an ADK artifact and store it in the pending-report
   buffer for WebSocket delivery.
"""

from __future__ import annotations

import asyncio
import io
import json
import logging
import os
import tempfile
import time
from datetime import datetime, timezone

from fpdf import FPDF
from google import genai
from google.adk.tools import ToolContext
from google.genai import types

from .frame_buffer import store_pending_report
from .schemas import REPORT_DATA_SCHEMA

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Vision / extraction model
# ---------------------------------------------------------------------------
REPORT_MODEL = os.getenv("REPORT_MODEL", "gemini-3-flash-preview")

_genai_client: genai.Client | None = None


def _get_client() -> genai.Client:
    global _genai_client
    if _genai_client is None:
        _genai_client = genai.Client()
    return _genai_client


# ---------------------------------------------------------------------------
# PDF builder
# ---------------------------------------------------------------------------


class _ReportPDF(FPDF):
    """Styled PDF for field-service reports."""

    _BLUE = (41, 98, 255)
    _DARK = (33, 33, 33)
    _GRAY = (100, 100, 100)
    _LIGHT_BG = (245, 245, 245)

    def header(self):
        self.set_font("Helvetica", "B", 20)
        self.set_text_color(*self._BLUE)
        self.cell(0, 12, "Field Service Report", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*self._BLUE)
        self.set_line_width(0.6)
        self.line(10, self.get_y(), self.w - 10, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*self._GRAY)
        self.cell(
            0, 10, f"Generated by Gemy AI  |  Page {self.page_no()}/{{nb}}", align="C"
        )

    # -- helpers --

    def section_title(self, title: str):
        self.ln(4)
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(*self._BLUE)
        self.cell(0, 9, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(200, 200, 200)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), self.w - 10, self.get_y())
        self.ln(3)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*self._DARK)
        self.multi_cell(0, 6, text)
        self.ln(2)

    def key_value(self, key: str, value: str):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*self._DARK)
        self.cell(45, 6, f"{key}:")
        self.set_font("Helvetica", "", 10)
        self.multi_cell(0, 6, value)
        self.ln(1)

    def step_row(self, step_num: int, description: str, outcome: str):
        y_start = self.get_y()
        # Step number badge
        self.set_fill_color(*self._BLUE)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 9)
        self.cell(8, 6, str(step_num), fill=True, align="C")
        self.set_text_color(*self._DARK)
        self.set_font("Helvetica", "", 10)
        x_after_badge = self.get_x() + 2
        self.set_x(x_after_badge)
        self.multi_cell(self.w - x_after_badge - 10, 6, description)
        # Outcome on next line indented
        self.set_x(x_after_badge)
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(*self._GRAY)
        self.multi_cell(self.w - x_after_badge - 10, 5, f"Outcome: {outcome}")
        self.ln(2)

    def add_captioned_image(
        self, image_bytes: bytes, caption: str, category: str, tmp_dir: str
    ):
        """Add an image with caption. Writes a temp file for FPDF."""
        tmp_path = os.path.join(tmp_dir, f"img_{id(image_bytes)}.jpg")
        with open(tmp_path, "wb") as f:
            f.write(image_bytes)

        # Category tag
        self.set_font("Helvetica", "B", 9)
        tag_colors = {
            "before": (255, 152, 0),
            "during": (33, 150, 243),
            "after": (76, 175, 80),
        }
        color = tag_colors.get(category, self._GRAY)
        self.set_fill_color(*color)
        self.set_text_color(255, 255, 255)
        self.cell(22, 5, category.upper(), fill=True, align="C")
        self.ln(2)

        # Check remaining page space; add page if needed
        avail = self.h - self.get_y() - 30
        img_w = min(self.w - 20, 170)
        if avail < 60:
            self.add_page()

        try:
            self.image(tmp_path, x=10, w=img_w)
        except Exception as exc:
            logger.warning("[ReportPDF] Could not embed image: %s", exc)
            self.set_font("Helvetica", "I", 9)
            self.set_text_color(*self._GRAY)
            self.cell(
                0, 6, "[Image could not be embedded]", new_x="LMARGIN", new_y="NEXT"
            )

        self.ln(2)
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(*self._DARK)
        self.multi_cell(0, 5, caption)
        self.ln(4)


# ---------------------------------------------------------------------------
# The ADK FunctionTool
# ---------------------------------------------------------------------------


async def generate_fix_report(
    conversation_summary: str, tool_context: ToolContext
) -> dict:
    """Generate a PDF service report summarising the completed repair.

    Call this tool after the repair is done and the user wants a report.
    Do NOT pass raw session history — compose a rich narrative summary
    of the conversation yourself before calling this tool.

    Args:
        conversation_summary: A detailed narrative summary of the entire
            repair session written by you (the agent). Must include:
            equipment type/model, problem description, your diagnosis,
            the repair plan, each guided step with its outcome, and
            whether the fix was successful. Write naturally — no JSON,
            no tool names, no internal details.
        tool_context: Injected by ADK — provides session & artifact access.

    Returns:
        A dict with ``status`` and ``message``.
    """
    session_id = tool_context.state.get("ws_session_id", tool_context.session.id)
    logger.info(
        "[ReportGen] generate_fix_report called — session=%s, summary=%d chars",
        session_id,
        len(conversation_summary),
    )

    # ------------------------------------------------------------------
    # 1. Gather image metadata from session state
    # ------------------------------------------------------------------
    processed_frames: list[dict] = tool_context.state.get("processed_frames", [])
    frames_metadata_str = ""
    if processed_frames:
        # Build a concise text representation of each frame's metadata
        entries = []
        for i, fm in enumerate(processed_frames):
            entry = (
                f"Image {i + 1}: artifact_name={fm.get('artifact_name', 'N/A')}, "
                f"type={fm.get('type', 'unknown')}, "
                f"timestamp={fm.get('timestamp', 0)}, "
                f"context={fm.get('context', '')[:300]}, "
                f"findings={fm.get('findings', '')[:300]}, "
                f"relevance={fm.get('relevance', 'unknown')}, "
                f"key_observations={fm.get('key_observations', [])}, "
                f"issues_detected={fm.get('issues_detected', [])}, "
                f"labels={fm.get('labels', [])}"
            )
            entries.append(entry)
        frames_metadata_str = "\n".join(entries)
    else:
        frames_metadata_str = "No images were captured during this session."

    # ------------------------------------------------------------------
    # 2. Extract structured report data via Gemini
    # ------------------------------------------------------------------
    prompt = (
        "You are a technical report writer. Given the following conversation "
        "summary of a field-service repair session and optional image metadata, "
        "extract a structured report.\n\n"
        "## Conversation Summary\n"
        f"{conversation_summary}\n\n"
        "## Available Images (metadata only)\n"
        f"{frames_metadata_str}\n\n"
        "## Instructions\n"
        "1. Extract equipment info, problem summary, final diagnosis, "
        "repair plan summary, execution log (numbered steps with outcomes), "
        "and follow-up recommendations.\n"
        "2. For selected_images: choose ONLY images that are relevant to "
        "the report. Use the metadata (context, findings, relevance, type, "
        "timestamp ordering) to decide which images best illustrate the "
        "repair — ideally pick images showing the problem (before), "
        "the repair in progress (during), and the final state (after). "
        "If no images are available or relevant, return an empty list.\n"
        "3. For each selected image, provide a descriptive caption and "
        'categorize as "before", "during", or "after".\n'
        "4. Be concise but thorough. Use professional language.\n"
        "Return the structured JSON."
    )

    try:
        client = _get_client()
        logger.info("[ReportGen] Calling %s for structured extraction…", REPORT_MODEL)
        response = await asyncio.wait_for(
            client.aio.models.generate_content(
                model=REPORT_MODEL,
                contents=[types.Part.from_text(text=prompt)],
                config=genai.types.GenerateContentConfig(
                    response_mime_type="application/json",
                    response_schema=REPORT_DATA_SCHEMA,
                ),
            ),
            timeout=45.0,
        )
        raw = response.text.strip() if response.text else ""
        logger.info("[ReportGen] Extraction response: %s", raw[:500])

        if not raw:
            return {
                "status": "error",
                "message": "The model returned an empty extraction. Please try again.",
            }

        report_data: dict = json.loads(raw)
    except asyncio.TimeoutError:
        logger.error("[ReportGen] Extraction timed out")
        return {
            "status": "error",
            "message": "Report extraction timed out — please try again.",
        }
    except Exception as e:
        logger.error("[ReportGen] Extraction failed: %s", e, exc_info=True)
        return {"status": "error", "message": f"Report extraction failed: {e}"}

    # ------------------------------------------------------------------
    # 3. Load selected images from ADK artifacts
    # ------------------------------------------------------------------
    selected_images = report_data.get("selected_images", [])
    loaded_images: list[dict] = []  # {caption, category, image_bytes}

    for img_sel in selected_images:
        artifact_name = img_sel.get("artifact_name", "")
        if not artifact_name:
            continue
        try:
            part = await tool_context.load_artifact(artifact_name)
            if part and part.inline_data and part.inline_data.data:
                loaded_images.append(
                    {
                        "caption": img_sel.get("caption", ""),
                        "category": img_sel.get("category", "during"),
                        "image_bytes": part.inline_data.data,
                    }
                )
                logger.info("[ReportGen] Loaded artifact %s", artifact_name)
            else:
                logger.warning(
                    "[ReportGen] Artifact %s returned no data", artifact_name
                )
        except Exception as e:
            logger.warning(
                "[ReportGen] Could not load artifact %s: %s", artifact_name, e
            )

    # ------------------------------------------------------------------
    # 4. Build PDF
    # ------------------------------------------------------------------
    now = datetime.now(timezone.utc)
    pdf = _ReportPDF(orientation="P", unit="mm", format="A4")
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Meta info
    pdf.key_value("Date", now.strftime("%B %d, %Y  %H:%M UTC"))
    pdf.key_value("Equipment", report_data.get("equipment_info", "N/A"))
    pdf.ln(2)

    # Problem Summary
    pdf.section_title("Problem Summary")
    pdf.body_text(report_data.get("problem_summary", "N/A"))

    # Diagnosis
    pdf.section_title("Final Diagnosis")
    pdf.body_text(report_data.get("final_diagnosis", "N/A"))

    # Repair Plan
    pdf.section_title("Repair Plan")
    pdf.body_text(report_data.get("repair_plan_summary", "N/A"))

    # Execution Log
    execution_log = report_data.get("execution_log", [])
    if execution_log:
        pdf.section_title("Step-by-Step Execution Log")
        for step in execution_log:
            pdf.step_row(
                step.get("step_number", 0),
                step.get("description", ""),
                step.get("outcome", ""),
            )

    # Equipment Images
    if loaded_images:
        pdf.section_title("Equipment Images")
        # Sort: before → during → after
        order = {"before": 0, "during": 1, "after": 2}
        loaded_images.sort(key=lambda x: order.get(x["category"], 1))

        with tempfile.TemporaryDirectory() as tmp_dir:
            for img in loaded_images:
                pdf.add_captioned_image(
                    image_bytes=img["image_bytes"],
                    caption=img["caption"],
                    category=img["category"],
                    tmp_dir=tmp_dir,
                )

    # Follow-Up Recommendations
    recommendations = report_data.get("follow_up_recommendations", [])
    if recommendations:
        pdf.section_title("Follow-Up Recommendations")
        for i, rec in enumerate(recommendations, 1):
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(33, 33, 33)
            pdf.cell(6, 6, f"{i}.")
            pdf.multi_cell(0, 6, rec)
            pdf.ln(1)

    # ------------------------------------------------------------------
    # 5. Export PDF bytes
    # ------------------------------------------------------------------
    pdf_bytes = pdf.output()

    logger.info("[ReportGen] PDF generated — %d bytes", len(pdf_bytes))

    # ------------------------------------------------------------------
    # 6. Save as ADK artifact + store for WebSocket delivery
    # ------------------------------------------------------------------
    artifact_name = f"fix_report_{int(time.time() * 1000)}.pdf"
    try:
        pdf_part = types.Part.from_bytes(data=pdf_bytes, mime_type="application/pdf")
        version = await tool_context.save_artifact(artifact_name, pdf_part)
        logger.info(
            "[ReportGen] Saved artifact %s (version %d)", artifact_name, version
        )
    except Exception as e:
        logger.error("[ReportGen] Artifact save failed: %s", e, exc_info=True)

    # Store in the delivery buffer for the downstream WebSocket task
    store_pending_report(session_id, pdf_bytes)

    return {
        "status": "success",
        "message": (
            "The service report has been generated and is being sent to your device. "
            "It contains the problem summary, diagnosis, repair steps, "
            f"{'images, ' if loaded_images else ''}"
            "and follow-up recommendations."
        ),
    }
